Model/Model/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

app/urls.py
from django import views
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.IndexView, name='index'),
    #path('create/', views.create, name='create'),
    path('create/active/', views.create_active, name='create_active'),

    #jason file
    path('users/', views.UsersView.as_view(), name='users_json'),
    path('jobs/', views.JobsView.as_view(), name='jobs_json'),
]

jinja/jinja/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

mblog/mblog/urls.py
from django.contrib import admin
from django.urls import path
from app.views import homepage
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',homepage),
]

praexiois/app/templates/app/create.html
{% load static %}
<html>
    <head>
        <title>Praexisio Astaxy UI Web</title>
    </head>

    <body>
        <div class="bg" style="border:2px purple solid;font-size:13px;background-color:purple;">
            <img src="{% static 'croppedlogo.png' %}" alt="company icon">
            <a href="{% url 'app:create' %}"><button>Create a new task</button></a>
            <a href="presonality.html"><button>Personalität</button></a>
            <a href="logout.html"><button>Log out</button></a>
            <a href="{% url 'app:index' %}"><button>[Home]</button></a>
            <form action="{% url 'app:create_active' %}" method="post">
                {% csrf_token %} 
                <fieldset>
                <input type="submit" value='submit'>Submit</button>
                </fieldset>
            </form>
        </div>
    </body>
</html>

praexiois/app/templates/app/logout.html
{% load static %}
<html>
    <head>
        <title>Praexisio Astaxy UI Web</title>
    </head>

    <body>
        <div class="bg" style="border:2px purple solid;font-size:13px;background-color:purple;">
            <img src="{% static 'croppedlogo.png' %}" alt="company icon">
            <a href="creatanewtask.html"><button>Create a new task</button></a>
            <a href="presonality.html"><button>Personalität</button></a>
            <a href="logout.html"><button>Log out</button></a>
	    <a href="index.php"><button>[Home]</button></a>
        </div>
    </body>
</html>